### ISSUE TITLE
加油！看好你。😬

### ISSUE THREAD

**Issue by devSC** [d33tah/strokes#13]

**Comment by d33tah** [comment]
@devSC 

谢谢。 你对这个电脑程序有什么意见吗？

**Comment by devSC** [comment]
等我有时间了，我会详细了解，并持续关注。😬 希望你再接再厉！

**Comment by hqzh** [comment]
welcome  to  china

**Comment by d33tah** [comment]
Thanks you @hqzh. It makes me wonder though - what exactly do you mean? I feel I'm missing a bit of context here.

**Comment by hqzh** [comment]
@d33tah Sorry for make you confused, as the Chinese saying goes: "It is better to travel ten thousand miles than to read ten thousand books."(读万卷书,行万里路)

**Comment by d33tah** [comment]
@hqzh I still don't know what you mean.

**Comment by hqzh** [comment]
@d33tah 你现在中文学的怎么样了?

**Comment by d33tah** [comment]
@hqzh 马马虎虎

**Comment by hqzh** [comment]
@d33tah 我上面的意思就是说,汉语博大精深,应该近距离感受她的文化底蕴.

**Comment by hqzh** [comment]
@d33tah 我感觉你有些拘谨.....

**Comment by nobody4t** [comment]
Hi，i would like to advice you guys talk in some instance app or email.

**Comment by d33tah** [comment]
@WandyLau Actually not a bad idea. Sorry for making noise!

@hqzh Could you contact me? My e-mail is my Github username at gmail.com
